// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.Context;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230906215148_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.AuthServer.Entities.AccessToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("AuthAccessToken");
                });

            modelBuilder.Entity("EntityLayer.AuthServer.Entities.RefreshToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("AuthRefreshToken");
                });

            modelBuilder.Entity("EntityLayer.Identity.Entities.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Identity.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<short?>("EmailConfirm")
                        .HasMaxLength(5)
                        .HasColumnType("smallint");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.AboutMe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("AboutMes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Description = "As a recent graduate in architecture with a passion for technology, I am excited to begin a new journey in the field of coding. Despite my lack of professional experience in this field, I am highly motivated and eager to learn and grow.I am committed to dedicating myself to studying coding concepts, practicing my skills, and seeking out opportunities to apply my knowledge to real-world projects. My background in architecture has equipped me with valuable skills such as creativity, problem-solving, and attention to detail, which I believe will be invaluable in my pursuit of a career in coding. My eagerness to learn and my passion for coding are what drive me. I am always eager to take on new challenges and to push myself to the limit in order to achieve my goals. Through my dedication and hard work, I am confident that I can make a meaningful contribution to any team or project that I am a part of.",
                            FileName = "Add Picture",
                            FileType = "Add Picture",
                            IsEdited = false,
                            IsPublished = true,
                            ResumeId = 1,
                            Title = "Software Developer London"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Description = "As a recent graduate in architecture with a passion for technology, I am excited to begin a new journey in the field of coding. Despite my lack of professional experience in this field, I am highly motivated and eager to learn and grow.I am committed to dedicating myself to studying coding concepts, practicing my skills, and seeking out opportunities to apply my knowledge to real-world projects. My background in architecture has equipped me with valuable skills such as creativity, problem-solving, and attention to detail, which I believe will be invaluable in my pursuit of a career in coding. My eagerness to learn and my passion for coding are what drive me. I am always eager to take on new challenges and to push myself to the limit in order to achieve my goals. Through my dedication and hard work, I am confident that I can make a meaningful contribution to any team or project that I am a part of.",
                            FileName = "Add Picture",
                            FileType = "Add Picture",
                            IsEdited = true,
                            IsPublished = false,
                            ResumeId = 2,
                            Title = "Software Developer Manchester"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Priorty")
                        .HasMaxLength(3)
                        .HasColumnType("smallint");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Date = "February 2023",
                            IsEdited = false,
                            IsPublished = true,
                            Location = "Udemy Course",
                            Priorty = (short)1,
                            ResumeId = 1,
                            Title = "Step by Step C#"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Date = "March 2023",
                            IsEdited = false,
                            IsPublished = true,
                            Location = "Udemy Course",
                            Priorty = (short)2,
                            ResumeId = 1,
                            Title = "Ms SQL with querries"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            Date = "April 2023",
                            IsEdited = true,
                            IsPublished = false,
                            Location = "Udemy Course",
                            Priorty = (short)1,
                            ResumeId = 2,
                            Title = "ASP.NET Framework MVC5"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            Date = "May 2023",
                            IsEdited = true,
                            IsPublished = false,
                            Location = "Udemy Course",
                            Priorty = (short)2,
                            ResumeId = 2,
                            Title = "ASP.NET Core 6 MVC"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AboutMeId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AboutMeId")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMeId = 1,
                            Address = "20 Cosmopolitan Court, 67 Main Avenue, Enfield, EN1 1GD",
                            CreatedDate = "06/09/2023",
                            Email = "hasan@gmail.com",
                            LocationUrl = "1",
                            Phone = "0785463212540"
                        },
                        new
                        {
                            Id = 2,
                            AboutMeId = 2,
                            Address = "44 Dowsett Road, Manchester, N17 9DD",
                            CreatedDate = "06/09/2023",
                            Email = "hasan@gmail.com",
                            LocationUrl = "2",
                            Phone = "0785463212540"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Priorty")
                        .HasMaxLength(3)
                        .HasColumnType("smallint");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Date = "2005 - 2010",
                            IsEdited = false,
                            IsPublished = true,
                            Location = "YILDIZ TECHNICAL UNIVERSITY",
                            Priorty = (short)1,
                            ResumeId = 1,
                            Title = "ARCHITECTURE"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Date = "2001 - 2005",
                            IsEdited = false,
                            IsPublished = true,
                            Location = "ATATURK HIGH SCHOOL",
                            Priorty = (short)2,
                            ResumeId = 1,
                            Title = "SCIENCE AND MATH"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            Date = "2005 - 2010",
                            IsEdited = true,
                            IsPublished = false,
                            Location = "YILDIZ TECHNICAL UNIVERSITY",
                            Priorty = (short)1,
                            ResumeId = 2,
                            Title = "ARCHITECTURE"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            Date = "2001 - 2005",
                            IsEdited = true,
                            IsPublished = false,
                            Location = "ATATURK HIGH SCHOOL",
                            Priorty = (short)2,
                            ResumeId = 2,
                            Title = "SCIENCE AND MATH"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Priorty")
                        .HasMaxLength(3)
                        .HasColumnType("smallint");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Date = "February 2023 - Present",
                            IsEdited = false,
                            IsPublished = true,
                            Location = "Freelance, London",
                            Priorty = (short)1,
                            ResumeId = 1,
                            Title = "Trainee Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Date = "April 2019 - Present",
                            IsEdited = false,
                            IsPublished = true,
                            Location = "B&H Design Ltd, London",
                            Priorty = (short)2,
                            ResumeId = 1,
                            Title = "Architect (Director)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            Date = "July 2011 - April 2019",
                            IsEdited = true,
                            IsPublished = false,
                            Location = "Gul-Na Architecture, Turkey",
                            Priorty = (short)1,
                            ResumeId = 2,
                            Title = "Architect (Director)"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            Date = "June 2010 - June 2011",
                            IsEdited = true,
                            IsPublished = false,
                            Location = "Engiz Architecture, Turkey",
                            Priorty = (short)2,
                            ResumeId = 2,
                            Title = "Architectural Assistant"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AboutMeId")
                        .HasColumnType("int");

                    b.Property<int>("Certificate")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("CodingLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DaysOfStudy")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("Project")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AboutMeId")
                        .IsUnique();

                    b.ToTable("Facts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMeId = 1,
                            Certificate = 8,
                            CodingLanguage = 3,
                            CreatedDate = "06/09/2023",
                            DaysOfStudy = 180,
                            Project = 12
                        },
                        new
                        {
                            Id = 2,
                            AboutMeId = 2,
                            Certificate = 10,
                            CodingLanguage = 2,
                            CreatedDate = "06/09/2023",
                            DaysOfStudy = 120,
                            Project = 15
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.HomePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ResumeCvFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResumeCvFileType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("HomePages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Description = "As a recent graduate in architecture with a passion for technology, I am excited to begin a new journey in the field of coding. Despite my lack of professional experience in this field.",
                            FullName = "Hasan Divarci",
                            IsEdited = false,
                            IsPublished = true,
                            ResumeCvFileName = "Add Pcture",
                            ResumeCvFileType = "Add Pcture",
                            ResumeId = 1,
                            VideoUrl = "https://youtu.be/RKKoABC31zk'"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Description = "As a recent graduate in architecture with a passion for technology, I am excited to begin a new journey in the field of coding. Despite my lack of professional experience in this field.",
                            FullName = "Hasan Divarci",
                            IsEdited = true,
                            IsPublished = false,
                            ResumeCvFileName = "Add Pcture",
                            ResumeCvFileType = "Add Pcture",
                            ResumeId = 2,
                            VideoUrl = "https://youtu.be/RKKoABC31zk'"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Description = "Welcome to the My Study Projects category. ",
                            Email = "adanali@adamlar.geldi",
                            IsEdited = false,
                            ResumeId = 1,
                            Sender = "Melih Canatan",
                            Subject = "Deneme Mesaji"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Description = "Welcome to the My Study Projects category2. ",
                            Email = "mallar@adamlar.geldi",
                            IsEdited = false,
                            ResumeId = 1,
                            Sender = "Tarik Canatan",
                            Subject = "Deneme Mesaji 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            Description = "Welcome to the My Study Projects category3. ",
                            Email = "antalyali@adamlar.geldi",
                            IsEdited = false,
                            ResumeId = 2,
                            Sender = "Kazim Canatan",
                            Subject = "Deneme Mesaji 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            Description = "Welcome to the My Study Projects category4. ",
                            Email = "bursali@adamlar.geldi",
                            IsEdited = false,
                            ResumeId = 2,
                            Sender = "Veli Canatan",
                            Subject = "Deneme Mesaji 4"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.NewsFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("NewsFeeds");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<int>("ProjectCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCategoryId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Description = "I'm excited to share details about my new project, which played a pivotal role in advancing my C# skills. This project had a strong emphasis on developing dynamic buttons with assigned dynamic missions, all accomplished through the implementation of complex algorithms. By implementing these complex algorithms, I not only expanded my knowledge of algorithmic concepts but also strengthened my problem-solving abilities. I gained valuable experience in analyzing complex problems, devising efficient solutions, and translating them into clean and well-structured code. This project served as a significant milestone in my C# journey, allowing me to consolidate my skills, broaden my horizons, and tackle more intricate programming challenges. I am proud of the achievements and growth I attained throughout this project, and I eagerly look forward to utilizing the knowledge and experiences gained to create innovative solutions in future endeavors. I'm excited about the opportunities that lie ahead and can't wait to continue expanding my expertise in C# and tackling even more advanced projects.",
                            ProjectCategoryId = 1,
                            ProjectDate = "2022 June",
                            Title = "Flight Ticket"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Description = "I am thrilled to share the details of my new project, which represents a significant milestone in my journey as a developer. Building upon the foundational skills I acquired in my first project, I dedicated this endeavor to two key areas: database connections and C# algorithms. In this project, I focused on establishing connections to databases, leveraging the capabilities of SQL and database query languages to interact with data effectively. I invested time and effort in learning about database design, normalization, and the principles of relational databases. I grasped concepts such as tables, primary keys, foreign keys, and relationships, which enabled me to design efficient and well-structured database schemas. Using C#, I honed my skills in implementing database connectivity through frameworks or libraries such as ADO.NET or Entity Framework. I gained proficiency in executing SQL queries, retrieving and manipulating data, and handling transactions to ensure data integrity. I am proud of the progress I made during this project, and I am excited to continue expanding my skills in database management, algorithmic problem-solving, and other facets of software development in future endeavors.",
                            ProjectCategoryId = 1,
                            ProjectDate = "2022 July",
                            Title = "Education Portal"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            Description = "I'm thrilled to share details about my latest project, a potential professional endeavor, developed using ASP.NET Core 6 MVC. This project represents a significant milestone in my journey as a developer, as it showcases my ability to apply solid disciplines, design patterns, clean code rules, and utilize various libraries and features. Throughout the development process, I prioritized adhering to solid disciplines. By applying this principle, I ensured a well-structured and maintainable codebase, enabling future modifications and enhancements with ease. In pursuit of clean code, I followed established coding conventions and guidelines, emphasizing readability, maintainability, and self-documentation. I employed meaningful naming conventions, utilized appropriate code comments, and organized the codebase logically to enhance collaboration and understandability. To handle user authentication and authorization, I leveraged identity libraries provided by ASP.NET Core, ensuring secure access control and user management. I implemented notification mechanisms to keep users informed about relevant updates, ensuring an engaging and interactive experience. With ASP.NET Core 6 MVC , I am confident in my ability to create innovative, scalable solutions that meet the evolving needs of the industry.",
                            ProjectCategoryId = 2,
                            ProjectDate = "2022 May",
                            Title = "Portfolio Web Site"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            Description = "I'm thrilled to share details about my latest project, a potential professional endeavor, developed using ASP.NET Core 6 MVC. This project represents a significant milestone in my journey as a developer, as it showcases my ability to apply solid disciplines, design patterns, clean code rules, and utilize various libraries and features. Throughout the development process, I prioritized adhering to solid disciplines. By applying this principle, I ensured a well-structured and maintainable codebase, enabling future modifications and enhancements with ease. In pursuit of clean code, I followed established coding conventions and guidelines, emphasizing readability, maintainability, and self-documentation. I employed meaningful naming conventions, utilized appropriate code comments, and organized the codebase logically to enhance collaboration and understandability. To handle user authentication and authorization, I leveraged identity libraries provided by ASP.NET Core, ensuring secure access control and user management. I implemented notification mechanisms to keep users informed about relevant updates, ensuring an engaging and interactive experience. With ASP.NET Core 6 MVC , I am confident in my ability to create innovative, scalable solutions that meet the evolving needs of the industry.",
                            ProjectCategoryId = 2,
                            ProjectDate = "2022 April",
                            Title = "Portfolio Web Site"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.ProjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId");

                    b.ToTable("ProjectCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Description = "Welcome to the My Study Projects category. ",
                            IsEdited = false,
                            IsPublished = true,
                            ResumeId = 1,
                            Title = "Study"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Description = "Welcome to the Real-World Projects category, where I present a series of practical.",
                            IsEdited = true,
                            IsPublished = false,
                            ResumeId = 2,
                            Title = "Real"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.ProjectImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = "06/09/2023",
                            FileName = "Add New File",
                            FileType = "Add New File",
                            ProjectId = 4
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            Description = "This is the best resume for now. Continue to use it.",
                            IsDeleted = false,
                            IsEdited = false,
                            IsPublished = true,
                            Title = "Software Developer London Resume"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            Description = "This is prepared for after ILR. Do not use this for now.",
                            IsDeleted = false,
                            IsEdited = true,
                            IsPublished = false,
                            Title = "Software Developer Manchester Resume"
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("Value")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IsEdited");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = "06/09/2023",
                            IsEdited = false,
                            IsPublished = true,
                            ResumeId = 1,
                            Title = "C# Coding Language",
                            Value = (byte)65
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = "06/09/2023",
                            IsEdited = false,
                            IsPublished = true,
                            ResumeId = 1,
                            Title = "Asp.Net Core 6 Mvc",
                            Value = (byte)85
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = "06/09/2023",
                            IsEdited = true,
                            IsPublished = false,
                            ResumeId = 2,
                            Title = "HTML",
                            Value = (byte)45
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = "06/09/2023",
                            IsEdited = true,
                            IsPublished = false,
                            ResumeId = 2,
                            Title = "CSS",
                            Value = (byte)65
                        });
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AboutMeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GitHub")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Twitter")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Youtube")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.HasIndex("AboutMeId")
                        .IsUnique();

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMeId = 1,
                            CreatedDate = "06/09/2023",
                            GitHub = "https://github.com/",
                            LinkedIn = "https://linkdin.com/",
                            Twitter = "https://twitter.com/",
                            Youtube = "https://youtube.com/"
                        },
                        new
                        {
                            Id = 2,
                            AboutMeId = 2,
                            CreatedDate = "06/09/2023",
                            GitHub = "https://github.com/",
                            LinkedIn = "https://linkdin.com/",
                            Twitter = "https://twitter.com/",
                            Youtube = "https://youtube.com/"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.AboutMe", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithOne("AboutMe")
                        .HasForeignKey("EntityLayer.WebApplication.Entities.AboutMe", "ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Certificate", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithMany("Certificates")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Contact", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.AboutMe", "AboutMe")
                        .WithOne("Contact")
                        .HasForeignKey("EntityLayer.WebApplication.Entities.Contact", "AboutMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutMe");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Education", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Experience", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithMany("Experiences")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Fact", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.AboutMe", "AboutMe")
                        .WithOne("Fact")
                        .HasForeignKey("EntityLayer.WebApplication.Entities.Fact", "AboutMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutMe");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.HomePage", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithOne("HomePage")
                        .HasForeignKey("EntityLayer.WebApplication.Entities.HomePage", "ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Message", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithMany("Messages")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Project", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.ProjectCategory", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.ProjectCategory", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithMany("ProjectCategories")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.ProjectImage", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Skill", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.SocialMedia", b =>
                {
                    b.HasOne("EntityLayer.WebApplication.Entities.AboutMe", "AboutMe")
                        .WithOne("SocialMedia")
                        .HasForeignKey("EntityLayer.WebApplication.Entities.SocialMedia", "AboutMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutMe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EntityLayer.Identity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EntityLayer.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EntityLayer.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EntityLayer.Identity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EntityLayer.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.AboutMe", b =>
                {
                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Fact")
                        .IsRequired();

                    b.Navigation("SocialMedia")
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Project", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.ProjectCategory", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EntityLayer.WebApplication.Entities.Resume", b =>
                {
                    b.Navigation("AboutMe")
                        .IsRequired();

                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("HomePage")
                        .IsRequired();

                    b.Navigation("Messages");

                    b.Navigation("ProjectCategories");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
